### ISSUE TITLE
Use HTTPS to load content and scripts inside web pages

### ISSUE THREAD

**Issue by neelabhg** [cs-education/sysassets#10]
If someone loads the pages inside `web/` over HTTPS (for example, [this link](https://cs-education.github.io/sysassets/web/chapter1.html)), videos, fonts, scripts, etc could not be loaded due to Mixed Content restrictions. (Also see cs-education/sysbuild#111).

Using HTTPS allows loading the pages using both HTTP and HTTPS and is more secure.

**Comment by angrave** [comment]
Fixed in bcc3456660bf7f14b34ea86d0ba8825063385913
