### ISSUE TITLE
Fix links in System Programming wiki-book to web pages hosted here

### ISSUE THREAD

**Issue by neelabhg** [cs-education/sysassets#11]
The [System Programming wiki-book](https://github.com/angrave/SystemProgramming/wiki) contains links to web pages hosted in this repository (in `web/`), but those links still point to http://angrave.github.io/sysassets, resulting in 404s.

The wiki is itself a git repository, which can be cloned and edited. This way all the links can be replaced using search tools instead of going through every wiki page.

I'm opening this issue here because those links were broken in the first place because this repository was transferred, and the System Programming wiki-book's repository does not have Issues enabled anyway.

**Comment by angrave** [comment]
Updated links using some perl pie ...

```
perl -p -i -e 's/angrave.github.io/cs-education.github.io/g' *.md
```

Found two instances ...

```
grep sysassets *
```

Files,-Part-1:-Working-with-files.md:We've already seen [open](http://cs-education.github.io/sysassets/web/chapter1.html) and fopen (todo link here) so let's look at some more advanced concepts.

POSIX,-Part-1:-Error-handling.md:Note, it is easy to believe that setting 'SA_RESTART' flag is sufficient to make this whole problem disappear. Unfortunately that's not true: there are still system calls that may return early and set `EINTR`! See [signal(7)](https://cs-education.github.io/sysassets/man_pages/html/man7/signal.7.html) for details.

**Comment by angrave** [comment]
Didn't find any more instances. So closing this issue
grep angrave.github *
