### ISSUE TITLE
GitHub's early access to Git Large File Storage support

### ISSUE THREAD

**Issue by neelabhg** [cs-education/sysassets#8]
As suggested by @scowalt and @angrave, [GitHub recently announced support for Git Large File Storage (LFS)](https://github.com/blog/1986-announcing-git-large-file-storage-lfs), which allows versioning large files. Perfect for this repository.

I just signed up the cs-education account for early access to use Git LFS. GitHub will be sending out invitations soon. This issue will track the status of the request.

**Comment by angrave** [comment]
Github large file support is limited to 1GB free traffic per month. All 23 lectures ~ 0.6GB per student. Perhaps it is better that we are not part of LFS right now.
